language: python
python:
  # - 2.7
  - 3.5
  - 3.6
services:
  - xvfb
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels chemdataextractor
  - conda info -a
  - conda create -q -n cde python=$TRAVIS_PYTHON_VERSION appdirs beautifulsoup4 click cssselect dawg lxml nltk numpy scipy pdfminer.six python-dateutil requests six python-crfsuite pyyaml pytest sphinx pandoc
  - source activate cde
  - pip install git+https://github.com/CambridgeMolecularEngineering/tabledataextractor.git
  - pip install nbsphinx==0.3.5 nbsphinx-link m2r ipython ipykernel sphinx-rtd-theme
  - pip install future==0.17.1
  - pip install unittest2==1.1.0
  - pip install playsound
  - python setup.py install
  - cde data download
script:
  - pytest
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      sphinx-build -b html ./docs/ ./docs/_build/html/;
    fi
